server:
  servlet:
    context-path: /blogi
spring:
  mvc:
    view:
      suffix: .html
  web:
    resources:
      static-locations:
        - classpath:/HTML/dummy
        - classpath:/JS/dummy
        - classpath:/CSS/dummy
        - classpath:/HTML/home-page
        - classpath:/JS/home-page
        - classpath:/CSS/home-page
        - classpath:/JS/home-page/filter
        - classpath:/JS/rest-api-caller
        - classpath:/JS/page-components-generator
        - classpath:/JS/events