server:
  servlet:
    context-path: /blogi
spring:
  mvc:
    view:
      suffix: .html
  web:
    resources:
      static-locations:
        - classpath:/HTML/dummy
        - classpath:/JS/dummy
        - classpath:/CSS/dummy